#!/bin/sh /etc/rc.common
START=98

USE_PROCD=1
PROG=/usr/sbin/bearDropper

start_service() {
  procd_open_instance
  procd_set_param command ${PROG} -m follow
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_set_param file /etc/config/bearDropper
  procd_set_param stdout 1
  procd_set_param stderr 1
  # procd_add_jail <- test in a jail # http://wiki.prplfoundation.org/wiki/Procd_reference
  procd_close_instance
}

service_triggers()
{
  procd_add_reload_trigger "bearDropper"
}
